# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/master/new/vivado_prj/audio_prj.srcs/sources_1/bd/audio_system/ip/audio_system_sys_cpu_0/audio_system_sys_cpu_0.xci
# IP: The module: 'audio_system_sys_cpu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_sys_cpu_0/audio_system_sys_cpu_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_system_sys_cpu_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/master/new/vivado_prj/audio_prj.srcs/sources_1/bd/audio_system/ip/audio_system_sys_cpu_0/audio_system_sys_cpu_0.xci
# IP: The module: 'audio_system_sys_cpu_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_sys_cpu_0/audio_system_sys_cpu_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_system_sys_cpu_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
