# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/master/new/vivado_prj/audio_prj.runs/synth_1/audio_system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/master/new/vivado_prj/audio_prj.cache/wt [current_project]
set_property parent.project_path C:/master/new/vivado_prj/audio_prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part_repo_paths {C:/Users/eirik/AppData/Roaming/Xilinx/Vivado/2024.1/xhub/board_store/xilinx_board_store} [current_project]
set_property board_part avnet.com:zedboard:part0:1.4 [current_project]
set_property ip_output_repo c:/master/new/vivado_prj/audio_prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/hdl/audio_system_wrapper.vhd
add_files C:/master/new/vivado_prj/audio_prj.srcs/sources_1/bd/audio_system/audio_system.bd
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_sys_cpu_0/audio_system_sys_cpu_0.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_aud_clkwiz_0/audio_system_aud_clkwiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_aud_clkwiz_0/audio_system_aud_clkwiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_aud_clkwiz_0/audio_system_aud_clkwiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_rstgen_0/audio_system_rstgen_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_rstgen_0/audio_system_rstgen_0.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_rstgen_0/audio_system_rstgen_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_xbar_0/audio_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_iic_codec_0/audio_system_iic_codec_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_iic_codec_0/audio_system_iic_codec_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/ip/audio_system_auto_pc_0/audio_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/audio_system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/master/new/audio_system.xdc
set_property used_in_implementation false [get_files C:/master/new/audio_system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/master/new/vivado_prj/audio_prj.srcs/utils_1/imports/synth_1/audio_system_wrapper.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top audio_system_wrapper -part xc7z020clg484-1 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef audio_system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file audio_system_wrapper_utilization_synth.rpt -pb audio_system_wrapper_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
