# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/master/new/audio_system.xdc

# Block Designs: bd/audio_system/audio_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system || ORIG_REF_NAME==audio_system} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_sys_cpu_0/audio_system_sys_cpu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_sys_cpu_0 || ORIG_REF_NAME==audio_system_sys_cpu_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_aud_clkwiz_0/audio_system_aud_clkwiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_aud_clkwiz_0 || ORIG_REF_NAME==audio_system_aud_clkwiz_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_rstgen_0/audio_system_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_rstgen_0 || ORIG_REF_NAME==audio_system_rstgen_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_xbar_0/audio_system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_xbar_0 || ORIG_REF_NAME==audio_system_xbar_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_axi_ic_0/audio_system_axi_ic_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_axi_ic_0 || ORIG_REF_NAME==audio_system_axi_ic_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_iic_codec_0/audio_system_iic_codec_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_iic_codec_0 || ORIG_REF_NAME==audio_system_iic_codec_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_u_dsp_0/audio_system_u_dsp_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_u_dsp_0 || ORIG_REF_NAME==audio_system_u_dsp_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_coeff_ctrl_0/audio_system_coeff_ctrl_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_coeff_ctrl_0 || ORIG_REF_NAME==audio_system_coeff_ctrl_0} -quiet] -quiet

# IP: bd/audio_system/ip/audio_system_auto_pc_0/audio_system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_system_auto_pc_0 || ORIG_REF_NAME==audio_system_auto_pc_0} -quiet] -quiet

# XDC: c:/master/new/vivado_prj/audio_prj.gen/sources_1/bd/audio_system/audio_system_ooc.xdc
